### ISSUE TITLE
Elasticsearch version compatibility

### ISSUE THREAD

**Issue by zifeo** [kamon-io/kamon-elasticsearch#2]
I'm using Kamon 6.6 and got that error. Which version of elasticsearch is supported? 

```shell
[error] java.lang.AbstractMethodError: kamon.elasticsearch.instrumentation.RequestInstrumentation$$anonfun$aroundExecuteListener$1$$anon$1.onFailure(Ljava/lang/Exception;)V
[error]         at org.elasticsearch.action.support.ThreadedActionListener$2.doRun(ThreadedActionListener.java:118)
[error]         at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:596)
[error]         at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
[error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[error]         at java.lang.Thread.run(Thread.java:745)

```

**Comment by ninadvps** [comment]
I can see its still using 2.4 es version.. which is really old... This needs to be updated.
